//alert("hello")
//console.log("Halo")
//let v= 5
//let s = "a"

// let tuoi = prompt("Nhap nam sinh")
// tuoi= 2020 - tuoi
// console.log(tuoi+" tuoi")

// let a = 5
// let b = "5"
// let c = "6"
// let d = a + b
// console.log(typeof(d));

//let a = prompt("Nhap gia tri a")
//let b = prompt("Nhap gia tri b")
// var person = prompt("Please enter your name", "Harry Potter")    // Harry Potter sẽ hiện ra mẫu cho người dùng


//let tongsonguoi = prompt("nhap tong so nguoi: ")
//let songuoideokinh = prompt("nhap nguoi deo kinh:")
//tongsonguoi = Number(tongsonguoi)
//songuoideokinh = Number(songuoideokinh)
//let tilenguoideokinh = (songuoideokinh/tongsonguoi)*100
//console.log(tilenguoideokinh)

// let x = 0
// while (x<3){
//    x++ //x=x+1
// }
// console.log(x)

// let x = 0
// while (x<3){
//    console.log(x++) //x=x+1
// }

// for (let y=1; y<4; y++){
//    console.log("Hello")
// }

// for (let y=1; y<4; y++)
// console.log("Hello")

//let solan = prompt("nhap so lan")
//for ( let count = 1; count <= solan; count++){
//    console.log("hello")
//}

// let solan = prompt("nhap so lan")
// let count = 0
// while(count<solan){
// console.log("hello")
// count ++
// }

// let i = 1;
//     while(i < 11){
//         if(i == 6){break;}
//         console.log(i);
//         i++;
//     }

// for(let x = 0 ; x<8; x++){
//     let ten  = prompt("nhap ten");
//     let tuoi  = prompt("nhap tuoi");
//     console.log(ten + " is " + tuoi + " years old")
// }

// for(let n=5; n<71;n+=5 ){
//     if(n%5 ==0){
//         console.log(n)
//     }
// }

// let n = 5
// while(n<71){
//     if(n%5 ==0){
//                console.log(n)
//                n+=5
//           }
// }